import Link from "next/link";
import { ArrowUpRight, BriefcaseBusiness, Plus, Search, Users } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";

type Project={id:string;name:string;client:string|null;code:string|null;color:string;status:"active"|"archived"|"deactivated";memberCount:number;minutes:number};
export function ProjectsView({projects}:{projects:Project[]}) {
  return <><PageHeader title="Projects" description="Track clients, people, and progress in one place." actions={<Link href="/projects/new" className="btn btn-primary"><Plus size={15}/>New project</Link>}/>
    {!projects.length?<section className="card grid min-h-[400px] place-items-center p-6 text-center"><div className="max-w-sm"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><BriefcaseBusiness size={24}/></span><h2 className="mt-5 text-xl font-bold">No projects yet</h2><p className="muted mt-2 text-sm leading-6">Create your first project to start organizing and recording your work.</p><Link href="/projects/new" className="btn btn-primary mt-5"><Plus size={15}/>Create project</Link></div></section>:<><div className="mb-5 flex h-10 max-w-md items-center gap-2 rounded-[10px] border border-[var(--border)] bg-[var(--surface)] px-3"><Search size={16} className="muted"/><input className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="Search projects or clients…"/></div><div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{projects.map(project=><Link href={`/projects/${project.id}`} key={project.id} className="card group p-5 transition hover:-translate-y-0.5 hover:border-[var(--accent)] hover:shadow-md"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl text-white" style={{background:project.color}}><BriefcaseBusiness size={18}/></span><div className="min-w-0 flex-1"><h2 className="truncate text-[15px] font-bold">{project.name}</h2><p className="muted mt-1 text-xs">{[project.client,project.code].filter(Boolean).join(" · ")||"Personal project"}</p></div><ArrowUpRight size={15} className="text-[var(--accent)] opacity-0 group-hover:opacity-100"/></div><div className="mt-6 flex items-end justify-between"><div><p className="muted text-[11px]">Tracked</p><p className="mt-1 text-xl font-bold">{Math.floor(project.minutes/60)}h {project.minutes%60}m</p></div><div className="flex items-center gap-2 text-xs"><Users size={14} className="muted"/><b>{project.memberCount}</b></div></div><p className="muted mt-4 text-[11px] capitalize">{project.status}</p></Link>)}</div></>}
  </>;
}
