"use client";

import Link from "next/link";
import { Archive, ArrowUpRight, BriefcaseBusiness, MoreHorizontal, Plus, Search, Users } from "lucide-react";
import { projects } from "@/lib/demo-data";
import { PageHeader } from "@/components/ui/page-header";

export function ProjectsView() {
  return <><PageHeader title="Projects" description="Track budgets, people, and progress in one place." actions={<Link href="/projects/new" className="btn btn-primary"><Plus size={15}/>New project</Link>}/>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row"><div className="flex h-10 flex-1 items-center gap-2 rounded-[10px] border border-[var(--border)] bg-[var(--surface)] px-3 sm:max-w-md"><Search size={16} className="muted"/><input className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="Search projects or clients…"/></div><select className="field sm:w-40"><option>All projects</option><option>Active</option><option>Archived</option></select></div>
    <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{projects.map((p)=><Link href={`/projects/${p.id}`} key={p.id} className="card group p-5 transition hover:-translate-y-0.5 hover:border-[color-mix(in_srgb,var(--accent)_40%,var(--border))] hover:shadow-md"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl text-white" style={{background:p.color}}><BriefcaseBusiness size={18}/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate text-[15px] font-bold">{p.name}</h2>{p.status==="Archived"&&<Archive size={13} className="muted"/>}</div><p className="muted mt-1 text-xs">{p.client} · {p.code}</p></div><button aria-label="Project actions" onClick={e=>e.preventDefault()} className="rounded-md p-1.5 opacity-0 hover:bg-[var(--surface-2)] group-hover:opacity-100"><MoreHorizontal size={17}/></button></div><div className="mt-6 flex items-end justify-between"><div><p className="muted text-[11px]">Tracked</p><p className="mt-1 text-xl font-bold">{p.hours}h <span className="muted text-xs font-normal">/ {p.budget}h</span></p></div><div className="flex items-center gap-2 text-xs"><Users size={14} className="muted"/><b>{p.members}</b><ArrowUpRight size={15} className="ml-2 text-[var(--accent)] opacity-0 group-hover:opacity-100"/></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[var(--surface-2)]"><div className="h-full rounded-full" style={{width:`${Math.min(100,p.hours/p.budget*100)}%`,background:p.color}}/></div><div className="muted mt-3 flex justify-between text-[11px]"><span>{Math.round(p.hours/p.budget*100)}% of budget</span><span>{p.status}</span></div></Link>)}</div>
  </>;
}
