import Link from "next/link";
import { desc, eq } from "drizzle-orm";
import { FileText, Plus } from "lucide-react";
import { getDb } from "@/db";
import { reports, projects } from "@/db/schema";
import { requireUser } from "@/lib/auth/session";
import { PageHeader } from "@/components/ui/page-header";

export async function ReportsPage(){const user=await requireUser();const rows=await getDb().select({id:reports.id,title:reports.title,status:reports.status,createdAt:reports.createdAt,project:projects.name}).from(reports).leftJoin(projects,eq(projects.id,reports.projectId)).where(eq(reports.creatorId,user.id)).orderBy(desc(reports.createdAt));return <><PageHeader title="Reports" description="Generate and share reports from your recorded time." actions={<Link href="/reports/new" className="btn btn-primary"><Plus size={15}/>New report</Link>}/>{!rows.length?<section className="card grid min-h-[400px] place-items-center p-6 text-center"><div className="max-w-sm"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><FileText size={24}/></span><h2 className="mt-5 text-xl font-bold">No reports generated</h2><p className="muted mt-2 text-sm leading-6">After logging time, build your first report to summarize and share the work.</p><Link href="/reports/new" className="btn btn-primary mt-5"><Plus size={15}/>Build report</Link></div></section>:<div className="card overflow-hidden">{rows.map(report=><Link href={`/reports/${report.id}`} key={report.id} className="flex items-center gap-3 border-b border-[var(--border)] p-4 last:border-0 hover:bg-[var(--surface-2)]"><span className="grid size-10 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><FileText size={17}/></span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{report.title}</b><p className="muted mt-1 text-xs">{report.project??"All projects"} · {new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(report.createdAt)}</p></div><span className="badge capitalize">{report.status}</span></Link>)}</div>}</>}
