import { and, eq, isNull } from "drizzle-orm";
import { FileBarChart } from "lucide-react";
import { getDb } from "@/db";
import { projectMembers, projects } from "@/db/schema";
import { requireUser } from "@/lib/auth/session";
import { PageHeader } from "@/components/ui/page-header";
import { generateReport } from "@/server/actions/reports";
export const dynamic="force-dynamic";
export default async function Page(){const current=await requireUser();const rows=await getDb().select({id:projects.id,name:projects.name}).from(projectMembers).innerJoin(projects,eq(projects.id,projectMembers.projectId)).where(and(eq(projectMembers.userId,current.id),isNull(projectMembers.revokedAt),isNull(projects.deletedAt)));const today=new Date().toISOString().slice(0,10);const monthStart=`${today.slice(0,8)}01`;return <><PageHeader title="Build a report" description="Create a report from your recorded time."/>{rows.length?<form action={generateReport} className="card max-w-xl p-5"><div className="grid gap-4"><div><label className="label">Report title</label><input name="title" required minLength={2} maxLength={120} className="field" placeholder="e.g. Monthly time summary"/></div><div><label className="label">Project</label><select name="projectId" className="field"><option value="">All projects (my entries)</option>{rows.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><label className="label">From</label><input name="from" required defaultValue={monthStart} max={today} className="field" type="date"/></div><div><label className="label">To</label><input name="to" required defaultValue={today} max={today} className="field" type="date"/></div></div><div><label className="label">Billable</label><select name="billable" className="field"><option value="any">All time</option><option value="yes">Billable only</option><option value="no">Non-billable only</option></select></div><button className="btn btn-primary w-fit"><FileBarChart size={15}/>Generate from my time</button></div></form>:<section className="card p-10 text-center"><p className="muted text-sm">Create a project and log time before generating a report.</p></section>}</>}
