import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { AwaitedReportData } from "./types";
import { formatDuration } from "@/lib/utils";

const styles = StyleSheet.create({
  page: { padding: 36, fontFamily: "Helvetica", fontSize: 9, color: "#202027" },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#ddddE4",
    paddingBottom: 18,
    marginBottom: 18,
  },
  brand: { fontSize: 16, fontWeight: 700, color: "#6558d3", marginBottom: 14 },
  title: { fontSize: 21, fontWeight: 700 },
  muted: { color: "#71717a", marginTop: 5 },
  summary: { flexDirection: "row", gap: 12, marginBottom: 22 },
  stat: {
    flexGrow: 1,
    padding: 12,
    backgroundColor: "#f6f6f8",
    borderRadius: 5,
  },
  statLabel: { fontSize: 8, color: "#71717a", marginBottom: 6 },
  statValue: { fontSize: 13, fontWeight: 700 },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeF2",
    paddingVertical: 8,
  },
  tableHead: {
    flexDirection: "row",
    backgroundColor: "#f6f6f8",
    paddingVertical: 7,
    fontWeight: 700,
  },
  date: { width: "13%", paddingHorizontal: 4 },
  member: { width: "15%", paddingHorizontal: 4 },
  project: { width: "17%", paddingHorizontal: 4 },
  description: { width: "29%", paddingHorizontal: 4 },
  hours: { width: "13%", paddingHorizontal: 4, textAlign: "right" },
  amount: { width: "13%", paddingHorizontal: 4, textAlign: "right" },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 36,
    right: 36,
    textAlign: "center",
    fontSize: 7,
    color: "#999",
  },
});

export function ReportPdf({ data }: { data: AwaitedReportData }) {
  const currency = data.report.currency ?? data.entries[0]?.currency ?? "USD";
  const amountLabel = Object.entries(data.summary.amounts).length
    ? Object.entries(data.summary.amounts)
        .map(([code, value]) =>
          new Intl.NumberFormat("en", {
            style: "currency",
            currency: code,
          }).format(value),
        )
        .join(" · ")
    : new Intl.NumberFormat("en", { style: "currency", currency }).format(0);
  return (
    <Document title={data.report.title} author="Tracker">
      <Page size="A4" style={styles.page} wrap>
        <View style={styles.header}>
          <Text style={styles.brand}>Tracker</Text>
          <Text style={styles.title}>{data.report.title}</Text>
          <Text style={styles.muted}>
            {data.report.projectName ?? "All projects"} ·{" "}
            {data.filters.from ?? "All time"} – {data.filters.to ?? "Present"}
          </Text>
        </View>
        <View style={styles.summary}>
          <View style={styles.stat}>
            <Text style={styles.statLabel}>TOTAL HOURS</Text>
            <Text style={styles.statValue}>
              {formatDuration(data.summary.totalMinutes)}
            </Text>
          </View>
          <View style={styles.stat}>
            <Text style={styles.statLabel}>BILLABLE</Text>
            <Text style={styles.statValue}>
              {formatDuration(data.summary.billableMinutes)}
            </Text>
          </View>
          <View style={styles.stat}>
            <Text style={styles.statLabel}>AMOUNT</Text>
            <Text style={styles.statValue}>{amountLabel}</Text>
          </View>
        </View>
        <View style={styles.tableHead} fixed>
          <Text style={styles.date}>Date</Text>
          <Text style={styles.member}>Member</Text>
          <Text style={styles.project}>Project</Text>
          <Text style={styles.description}>Description</Text>
          <Text style={styles.hours}>Hours</Text>
          <Text style={styles.amount}>Amount</Text>
        </View>
        {data.entries.map((entry) => (
          <View key={entry.id} style={styles.row} wrap={false}>
            <Text style={styles.date}>{entry.date}</Text>
            <Text style={styles.member}>{entry.member}</Text>
            <Text style={styles.project}>{entry.project}</Text>
            <Text style={styles.description}>{entry.description}</Text>
            <Text style={styles.hours}>
              {formatDuration(entry.durationMinutes)}
            </Text>
            <Text style={styles.amount}>
              {entry.billable
                ? new Intl.NumberFormat("en", {
                    style: "currency",
                    currency: entry.currency,
                  }).format(
                    (entry.durationMinutes / 60) *
                      Number(entry.hourlyRate ?? 0),
                  )
                : "—"}
            </Text>
          </View>
        ))}
        <Text
          style={styles.footer}
          fixed
          render={({ pageNumber, totalPages }) =>
            `Generated by Tracker · Page ${pageNumber} of ${totalPages}`
          }
        />
      </Page>
    </Document>
  );
}
