import { and, eq, inArray, isNull } from "drizzle-orm";
import { Users } from "lucide-react";
import { getDb } from "@/db";
import { projectMembers, projects, user } from "@/db/schema";
import { requireUser } from "@/lib/auth/session";
import { PageHeader } from "@/components/ui/page-header";
import { initials } from "@/lib/utils";

export async function TeamPage(){const current=await requireUser();const db=getDb();const own=await db.select({projectId:projectMembers.projectId}).from(projectMembers).innerJoin(projects,eq(projects.id,projectMembers.projectId)).where(and(eq(projectMembers.userId,current.id),isNull(projectMembers.revokedAt),isNull(projects.deletedAt)));const projectIds=own.map(row=>row.projectId);const rows=projectIds.length?await db.select({id:user.id,name:user.name,email:user.email,role:projectMembers.role}).from(projectMembers).innerJoin(user,eq(user.id,projectMembers.userId)).where(and(inArray(projectMembers.projectId,projectIds),isNull(projectMembers.revokedAt))):[];const members=[...new Map(rows.map(row=>[row.id,row])).values()];return <><PageHeader title="Team" description="People who share access to your projects."/>{!members.length?<section className="card grid min-h-[360px] place-items-center text-center"><div><Users className="mx-auto text-[var(--accent)]"/><h2 className="mt-4 text-lg font-bold">No team members yet</h2><p className="muted mt-2 text-sm">Invite members from a project when you are ready.</p></div></section>:<div className="card overflow-hidden">{members.map(member=><div key={member.id} className="flex items-center gap-3 border-b border-[var(--border)] p-4 last:border-0"><span className="grid size-10 place-items-center rounded-xl bg-[var(--surface-2)] text-xs font-bold">{initials(member.name)}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{member.name}{member.id===current.id?" (you)":""}</b><span className="muted block truncate text-xs">{member.email}</span></div><span className="badge capitalize">{member.role}</span></div>)}</div>}</>}
